export const NEW_CAR_DATA = "NEW_CAR_DATA",
    USED_CAR_DATA = "USED_CAR_DATA",
    GET_INVENTORY_DATA = "GET_INVENTORY_DATA";

export const ADD_TO_URL = "ADD_TO_URL",
    REMOVE_FROM_URL = "REMOVE_FROM_URL",
    RESET_URL = "RESET_URL";

export const OPTION1 = "OPTION1",
    OPTION2 = "OPTION2",
    OPTION3 = "OPTION3",
    OPTION4 = "OPTION4",
    OPTION5 = "OPTION5",
    RESET_OPTIONS = "RESET_OPTIONS";

export const OPTION1SELECTED = "OPTION1_SELECTED",
    OPTION2SELECTED = "OPTION2_SELECTED",
    OPTION3SELECTED = "OPTION3_SELECTED",
    OPTION4SELECTED = "OPTION4_SELECTED",
    OPTION5SELECTED = "OPTION5_SELECTED",
    RESET_SELECTED = "RESET_SELECTED";

export const OPTION1_COLOR = "OPTION1_COLOR",
    OPTION2_COLOR = "OPTION2_COLOR";

export const ADD_OPTION_SELECTED = "ADD_OPTION_SELECTED",
    REMOVE_OPTIONS_SELECTED = "REMOVE_OPTIONS_SELECTED",
    RESET_OPTION_SELECTED = "RESET_OPTION_SELECTED";

export const ADD_TO_COMPARE = "ADD_TO_COMPARE",
    REMOVE_FROM_COMPARE = "REMOVE_FROM_COMPARE";

export const ADD_MESSAGE_SNACKBAR = "ADD_MESSAGE_SNACKBAR",
    RESET_MESSAGE_SNACKBAR = "RESET_MESSAGE_SNACKBAR";

export const UPDATE_INVENTORY_SORT = "UPDATE_INVENTORY_SORT";

export const UPDATE_INVENTORY_LAYOUT = "UPDATE_INVENTORY_LAYOUT";

